[project]
name = "ai-agent"
version = "0.1.0"
dependencies = [
    "quart==0.19.0",
    "uvicorn==0.30.1",
    "pydantic==2.7.1",
    "python-dotenv==1.0.1",
]

[project.optional-dependencies]
dev = [
    "pytest==8.2.0",
    "black==24.4.2",
    "isort==5.13.2",
]

[tool.black]
line-length = 88