# Import BaseModel from pydantic.
# Pydantic is used for data validation and parsing based on Python type hints.
from pydantic import BaseModel

# Define a request model for chat messages.
# This model is used to validate the incoming JSON data for a chat API endpoint.
class ChatRequest(BaseModel):
    # The message sent by the user (required).
    message: str
    
    # An optional session ID to track conversation context.
    # If not provided, a new session can be created by the server.
    session_id: str | None = None

# Define a response model for chat replies.
# This model is used to structure and validate the outgoing JSON data from the API.
class ChatResponse(BaseModel):
    # The reply text generated by the AI or chatbot.
    reply: str
    
    # The session ID associated with this conversation.
    # This helps maintain continuity across messages.
    session_id: str
